# Scala CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/sample-config/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx256m
      TERM: dumb

    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - dependency-cache-
      - run: ./gradlew build checkScalafmt
      - run: docker build -t adobeapiplatform/mesos-actor .
      - save_cache:
          paths:
            - ~/.gradle
          key: dependency-cache-{{ checksum "build.gradle" }}

